name: lpp-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - lipyphilic
  - ipywidgets
  - jupyter_contrib_nbextensions
  - widgetsnbextension
  - joblib
  - scikit-learn
  - hmmlearn>=3.0
  - pytables
  - tabulate
