name: lpp-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - lipyphilic
  - ipykernel
  - ipywidgets
  - joblib
  - scikit-learn
  - hmmlearn
  - pytables
  - tabulate
